[package]
name = "ordered-map"
version = "0.2.1"
description = "HashMap that also stores the order of inserted entries"
repository = "https://github.com/vporton/ordered-map.mo"
keywords = [ "hashmap", "hash-map", "ordered", "order" ]
license = "MIT"

[dependencies]
base = "0.12.1"
